var rep_table= [

{first_name: "Ralph",last_name: "Abraham",bioguide_id: "A000374",disposition: "supports",whipcount_id: "8081"},
{first_name: "Alma",last_name: "Adams",bioguide_id: "A000370",disposition: "oppose",whipcount_id: "7936"},
{first_name: "Robert",last_name: "Aderholt",bioguide_id: "A000055",disposition: "oppose",whipcount_id: "7650"},
{first_name: "Pete",last_name: "Aguilar",bioguide_id: "A000371",disposition: "oppose",whipcount_id: "7934"},
{first_name: "Rick",last_name: "Allen",bioguide_id: "A000372",disposition: "supports",whipcount_id: "7765"},
{first_name: "Justin",last_name: "Amash",bioguide_id: "A000367",disposition: "oppose",whipcount_id: "7661"},
{first_name: "Mark",last_name: "Amodei",bioguide_id: "A000369",disposition: "supports",whipcount_id: "8062"},
{first_name: "Brad",last_name: "Ashford",bioguide_id: "A000373",disposition: "unknown",whipcount_id: "7959", phone: "202-225-4155"},
{first_name: "Brian",last_name: "Babin",bioguide_id: "B001291",disposition: "supports",whipcount_id: "8184"},
{first_name: "Lou",last_name: "Barletta",bioguide_id: "B001269",disposition: "supports",whipcount_id: "7890"},
{first_name: "Garland",last_name: "Barr",bioguide_id: "B001282",disposition: "supports",whipcount_id: "8052"},
{first_name: "Joe",last_name: "Barton",bioguide_id: "B000213",disposition: "supports",whipcount_id: "8055"},
{first_name: "Karen",last_name: "Bass",bioguide_id: "B001270",disposition: "oppose",whipcount_id: "7957"},
{first_name: "Joyce",last_name: "Beatty",bioguide_id: "B001281",disposition: "oppose",whipcount_id: "7697"},
{first_name: "Xavier",last_name: "Becerra",bioguide_id: "B000287",disposition: "oppose",whipcount_id: "7945"},
{first_name: "Dan",last_name: "Benishek",bioguide_id: "B001271",disposition: "supports",whipcount_id: "7652"},
{first_name: "Ami",last_name: "Bera",bioguide_id: "B001287",disposition: "unknown",whipcount_id: "7775", phone: "202-225-5716"},
{first_name: "Donald",last_name: "Beyer",bioguide_id: "B001292",disposition: "unknown",whipcount_id: "7742", phone: "202-225-4376"},
{first_name: "Gus",last_name: "Bilirakis",bioguide_id: "B001257",disposition: "supports",whipcount_id: "8148"},
{first_name: "Mike",last_name: "Bishop",bioguide_id: "B001293",disposition: "supports",whipcount_id: "7692"},
{first_name: "Rob",last_name: "Bishop",bioguide_id: "B001250",disposition: "supports",whipcount_id: "7685"},
{first_name: "Sanford",last_name: "Bishop",bioguide_id: "B000490",disposition: "oppose",whipcount_id: "7710"},
{first_name: "Diane",last_name: "Black",bioguide_id: "B001273",disposition: "supports",whipcount_id: "8006"},
{first_name: "Marsha",last_name: "Blackburn",bioguide_id: "B001243",disposition: "supports",whipcount_id: "8010"},
{first_name: "Rod",last_name: "Blum",bioguide_id: "B001294",disposition: "supports",whipcount_id: "7799"},
{first_name: "Earl",last_name: "Blumenauer",bioguide_id: "B000574",disposition: "unknown ",whipcount_id: "7825",phone: "202-225-4811"},
{first_name: "Suzanne",last_name: "Bonamici",bioguide_id: "B001278",disposition: "unknown",whipcount_id: "7816",phone: "202-225-0855"},
{first_name: "Mike",last_name: "Bost",bioguide_id: "B001295",disposition: "supports",whipcount_id: "7913"},
{first_name: "Charles",last_name: "Boustany",bioguide_id: "B001255",disposition: "supports",whipcount_id: "8071"},
{first_name: "Brendan",last_name: "Boyle",bioguide_id: "B001296",disposition: "oppose",whipcount_id: "7900"},
{first_name: "Kevin",last_name: "Brady",bioguide_id: "B000755",disposition: "supports",whipcount_id: "8065"},
{first_name: "Robert",last_name: "Brady",bioguide_id: "B001227",disposition: "oppose",whipcount_id: "7844"},
{first_name: "David",last_name: "Brat",bioguide_id: "B001290",disposition: "oppose",whipcount_id: "7736"},
{first_name: "Jim",last_name: "Bridenstine",bioguide_id: "B001283",disposition: "oppose",whipcount_id: "7794"},
{first_name: "Mo",last_name: "Brooks",bioguide_id: "B001274",disposition: "oppose",whipcount_id: "7654"},
{first_name: "Susan",last_name: "Brooks",bioguide_id: "B001284",disposition: "supports",whipcount_id: "7984"},
{first_name: "Corrine",last_name: "Brown",bioguide_id: "B000911",disposition: "oppose",whipcount_id: "8117"},
{first_name: "Julia",last_name: "Brownley",bioguide_id: "B001285",disposition: "oppose",whipcount_id: "7909"},
{first_name: "Vern",last_name: "Buchanan",bioguide_id: "B001260",disposition: "supports",whipcount_id: "7651"},
{first_name: "Ken",last_name: "Buck",bioguide_id: "B001297",disposition: "oppose",whipcount_id: "8047"},
{first_name: "Larry",last_name: "Bucshon",bioguide_id: "B001275",disposition: "supports",whipcount_id: "7997"},
{first_name: "Michael",last_name: "Burgess",bioguide_id: "B001248",disposition: "oppose",whipcount_id: "8151"},
{first_name: "Cheri",last_name: "Bustos",bioguide_id: "B001286",disposition: "oppose",whipcount_id: "7944"},
{first_name: "George",last_name: "Butterfield",bioguide_id: "B001251",disposition: "oppose",whipcount_id: "7875"},
{first_name: "Bradley",last_name: "Byrne",bioguide_id: "B001289",disposition: "did not vote",whipcount_id: "7643"},
{first_name: "Tony",last_name: "CÃ¡rdenas",bioguide_id: "C001097",disposition: "oppose",whipcount_id: "7925"},
{first_name: "Ken",last_name: "Calvert",bioguide_id: "C000059",disposition: "supports",whipcount_id: "7978"},
{first_name: "Lois",last_name: "Capps",bioguide_id: "C001036",disposition: "oppose",whipcount_id: "7899"},
{first_name: "Michael",last_name: "Capuano",bioguide_id: "C001037",disposition: "oppose",whipcount_id: "8129"},
{first_name: "John",last_name: "Carney",bioguide_id: "C001083",disposition: "oppose",whipcount_id: "8098"},
{first_name: "AndrÃ©",last_name: "Carson",bioguide_id: "C001072",disposition: "oppose",whipcount_id: "7991"},
{first_name: "Buddy",last_name: "Carter",bioguide_id: "C001103",disposition: "supports",whipcount_id: "7704"},
{first_name: "John",last_name: "Carter",bioguide_id: "C001051",disposition: "supports",whipcount_id: "7674"},
{first_name: "Matthew",last_name: "Cartwright",bioguide_id: "C001090",disposition: "oppose",whipcount_id: "7920"},
{first_name: "Kathy",last_name: "Castor",bioguide_id: "C001066",disposition: "oppose",whipcount_id: "7645"},
{first_name: "Joaquin",last_name: "Castro",bioguide_id: "C001091",disposition: "oppose",whipcount_id: "8120"},
{first_name: "Steve",last_name: "Chabot",bioguide_id: "C000266",disposition: "supports",whipcount_id: "7683"},
{first_name: "Jason",last_name: "Chaffetz",bioguide_id: "C001076",disposition: "supports",whipcount_id: "7696"},
{first_name: "Judy",last_name: "Chu",bioguide_id: "C001080",disposition: "oppose",whipcount_id: "7914"},
{first_name: "David",last_name: "Cicilline",bioguide_id: "C001084",disposition: "oppose",whipcount_id: "7935"},
{first_name: "Katherine",last_name: "Clark",bioguide_id: "C001101",disposition: "oppose",whipcount_id: "8118"},
{first_name: "Yvette",last_name: "Clarke",bioguide_id: "C001067",disposition: "oppose",whipcount_id: "8122"},
{first_name: "Curtis",last_name: "Clawson",bioguide_id: "C001102",disposition: "oppose",whipcount_id: "7663"},
{first_name: "Wm.",last_name: "Clay",bioguide_id: "C001049",disposition: "oppose",whipcount_id: "7783"},
{first_name: "Emanuel",last_name: "Cleaver",bioguide_id: "C001061",disposition: "oppose",whipcount_id: "7808"},
{first_name: "James",last_name: "Clyburn",bioguide_id: "C000537",disposition: "did not vote",whipcount_id: "7973"},
{first_name: "Mike",last_name: "Coffman",bioguide_id: "C001077",disposition: "supports",whipcount_id: "8057"},
{first_name: "Steve",last_name: "Cohen",bioguide_id: "C001068",disposition: "oppose",whipcount_id: "8024"},
{first_name: "Tom",last_name: "Cole",bioguide_id: "C001053",disposition: "supports",whipcount_id: "7806"},
{first_name: "Chris",last_name: "Collins",bioguide_id: "C001092",disposition: "oppose",whipcount_id: "7665"},
{first_name: "Doug",last_name: "Collins",bioguide_id: "C001093",disposition: "oppose",whipcount_id: "7749"},
{first_name: "Barbara",last_name: "Comstock",bioguide_id: "C001105",disposition: "supports",whipcount_id: "7754"},
{first_name: "K.",last_name: "Conaway",bioguide_id: "C001062",disposition: "supports",whipcount_id: "8077"},
{first_name: "Gerald",last_name: "Connolly",bioguide_id: "C001078",disposition: "unknown",whipcount_id: "7761",phone: "202-225-1492"},
{first_name: "John",last_name: "Conyers",bioguide_id: "C000714",disposition: "oppose",whipcount_id: "7723"},
{first_name: "Paul",last_name: "Cook",bioguide_id: "C001094",disposition: "oppose",whipcount_id: "7781"},
{first_name: "Jim",last_name: "Cooper",bioguide_id: "C000754",disposition: "unknown",whipcount_id: "8000",phone: "202-225-4311"},
{first_name: "Jim",last_name: "Costa",bioguide_id: "C001059",disposition: "unknown",whipcount_id: "7847",phone: "202-225-3341"},
{first_name: "Ryan",last_name: "Costello",bioguide_id: "C001106",disposition: "supports",whipcount_id: "7869"},
{first_name: "Joe",last_name: "Courtney",bioguide_id: "C001069",disposition: "oppose",whipcount_id: "8075"},
{first_name: "Kevin",last_name: "Cramer",bioguide_id: "C001096",disposition: "supports",whipcount_id: "7946"},
{first_name: "Eric",last_name: "Crawford",bioguide_id: "C001087",disposition: "supports",whipcount_id: "7666"},
{first_name: "Ander",last_name: "Crenshaw",bioguide_id: "C001045",disposition: "supports",whipcount_id: "8113"},
{first_name: "Joseph",last_name: "Crowley",bioguide_id: "C001038",disposition: "oppose",whipcount_id: "8149"},
{first_name: "Henry",last_name: "Cuellar",bioguide_id: "C001063",disposition: "unknown",whipcount_id: "8159",phone: "202-225-1640"},
{first_name: "John",last_name: "Culberson",bioguide_id: "C001048",disposition: "supports",whipcount_id: "8060"},
{first_name: "Elijah",last_name: "Cummings",bioguide_id: "C000984",disposition: "oppose",whipcount_id: "8175"},
{first_name: "Carlos",last_name: "Curbelo",bioguide_id: "C001107",disposition: "supports ",whipcount_id: "8186"},
{first_name: "Warren",last_name: "Davidson",bioguide_id: "D000626",disposition: "oppose",whipcount_id: "7728"},
{first_name: "Danny",last_name: "Davis",bioguide_id: "D000096",disposition: "oppose",whipcount_id: "7883"},
{first_name: "Rodney",last_name: "Davis",bioguide_id: "D000619",disposition: "did not vote",whipcount_id: "7918"},
{first_name: "Susan",last_name: "Davis",bioguide_id: "D000598",disposition: "unknown ",whipcount_id: "8027",phone: "202-225-2040"},
{first_name: "Peter",last_name: "DeFazio",bioguide_id: "D000191",disposition: "oppose",whipcount_id: "7831"},
{first_name: "Diana",last_name: "DeGette",bioguide_id: "D000197",disposition: "oppose",whipcount_id: "8031"},
{first_name: "John",last_name: "Delaney",bioguide_id: "D000620",disposition: "unknown ",whipcount_id: "8172",phone: "202-225-2721"},
{first_name: "Rosa",last_name: "DeLauro",bioguide_id: "D000216",disposition: "oppose",whipcount_id: "8078"},
{first_name: "Suzan",last_name: "DelBene",bioguide_id: "D000617",disposition: "unknown ",whipcount_id: "7779",phone: "202-225-6311"},
{first_name: "Jeff",last_name: "Denham",bioguide_id: "D000612",disposition: "supports",whipcount_id: "7802"},
{first_name: "Charles",last_name: "Dent",bioguide_id: "D000604",disposition: "supports",whipcount_id: "7912"},
{first_name: "Ron",last_name: "DeSantis",bioguide_id: "D000621",disposition: "supports",whipcount_id: "8121"},
{first_name: "Mark",last_name: "DeSaulnier",bioguide_id: "D000623",disposition: "oppose",whipcount_id: "7807"},
{first_name: "Scott",last_name: "DesJarlais",bioguide_id: "D000616",disposition: "supports",whipcount_id: "7995"},
{first_name: "Theodore",last_name: "Deutch",bioguide_id: "D000610",disposition: "oppose",whipcount_id: "7675"},
{first_name: "Mario",last_name: "Diaz-Balart",bioguide_id: "D000600",disposition: "supports",whipcount_id: "7698"},
{first_name: "Debbie",last_name: "Dingell",bioguide_id: "D000624",disposition: "oppose",whipcount_id: "7717"},
{first_name: "Lloyd",last_name: "Doggett",bioguide_id: "D000399",disposition: "oppose",whipcount_id: "8183"},
{first_name: "Bob",last_name: "Dold",bioguide_id: "D000613",disposition: "supports",whipcount_id: "7898"},
{first_name: "Daniel",last_name: "Donovan",bioguide_id: "D000625",disposition: "oppose",whipcount_id: "8133"},
{first_name: "Michael",last_name: "Doyle",bioguide_id: "D000482",disposition: "oppose",whipcount_id: "7906"},
{first_name: "Tammy",last_name: "Duckworth",bioguide_id: "D000622",disposition: "oppose",whipcount_id: "7889"},
{first_name: "Sean",last_name: "Duffy",bioguide_id: "D000614",disposition: "supports",whipcount_id: "7884"},
{first_name: "Jeff",last_name: "Duncan",bioguide_id: "D000615",disposition: "oppose",whipcount_id: "7956"},
{first_name: "John",last_name: "Duncan",bioguide_id: "D000533",disposition: "oppose",whipcount_id: "7986"},
{first_name: "Donna",last_name: "Edwards",bioguide_id: "E000290",disposition: "oppose",whipcount_id: "8165"},
{first_name: "Keith",last_name: "Ellison",bioguide_id: "E000288",disposition: "oppose",whipcount_id: "7758"},
{first_name: "Renee",last_name: "Ellmers",bioguide_id: "E000291",disposition: "supports",whipcount_id: "7880"},
{first_name: "Tom",last_name: "Emmer",bioguide_id: "E000294",disposition: "oppose",whipcount_id: "7763"},
{first_name: "Eliot",last_name: "Engel",bioguide_id: "E000179",disposition: "oppose",whipcount_id: "8156"},
{first_name: "Anna",last_name: "Eshoo",bioguide_id: "E000215",disposition: "oppose",whipcount_id: "7862"},
{first_name: "Elizabeth",last_name: "Esty",bioguide_id: "E000293",disposition: "oppose",whipcount_id: "8087"},
{first_name: "Blake",last_name: "Farenthold",bioguide_id: "F000460",disposition: "oppose",whipcount_id: "8155"},
{first_name: "Sam",last_name: "Farr",bioguide_id: "F000030",disposition: "unknown",whipcount_id: "7873",phone: "202-225-2861"},
{first_name: "Stephen",last_name: "Fincher",bioguide_id: "F000458",disposition: "supports",whipcount_id: "8016"},
{first_name: "Michael",last_name: "Fitzpatrick",bioguide_id: "F000451",disposition: "supports",whipcount_id: "7877"},
{first_name: "Charles",last_name: "Fleischmann",bioguide_id: "F000459",disposition: "supports",whipcount_id: "7992"},
{first_name: "John",last_name: "Fleming",bioguide_id: "F000456",disposition: "oppose",whipcount_id: "8076"},
{first_name: "Bill",last_name: "Flores",bioguide_id: "F000461",disposition: "supports",whipcount_id: "8106"},
{first_name: "J.",last_name: "Forbes",bioguide_id: "F000445",disposition: "supports",whipcount_id: "7719"},
{first_name: "Jeff",last_name: "Fortenberry",bioguide_id: "F000449",disposition: "supports",whipcount_id: "7953"},
{first_name: "Bill",last_name: "Foster",bioguide_id: "F000454",disposition: "oppose",whipcount_id: "7907"},
{first_name: "Virginia",last_name: "Foxx",bioguide_id: "F000450",disposition: "supports",whipcount_id: "7901"},
{first_name: "Lois",last_name: "Frankel",bioguide_id: "F000462",disposition: "oppose",whipcount_id: "7681"},
{first_name: "Trent",last_name: "Franks",bioguide_id: "F000448",disposition: "supports",whipcount_id: "7738"},
{first_name: "Rodney",last_name: "Frelinghuysen",bioguide_id: "F000372",disposition: "supports",whipcount_id: "8028"},
{first_name: "Marcia",last_name: "Fudge",bioguide_id: "F000455",disposition: "oppose",whipcount_id: "7746"},
{first_name: "Tulsi",last_name: "Gabbard",bioguide_id: "G000571",disposition: "oppose",whipcount_id: "7791"},
{first_name: "Ruben",last_name: "Gallego",bioguide_id: "G000574",disposition: "oppose",whipcount_id: "7732"},
{first_name: "John",last_name: "Garamendi",bioguide_id: "G000559",disposition: "oppose",whipcount_id: "7753"},
{first_name: "Scott",last_name: "Garrett",bioguide_id: "G000548",disposition: "oppose",whipcount_id: "8003"},
{first_name: "Bob",last_name: "Gibbs",bioguide_id: "G000563",disposition: "supports",whipcount_id: "7721"},
{first_name: "Christopher",last_name: "Gibson",bioguide_id: "G000564",disposition: "oppose",whipcount_id: "8166"},
{first_name: "Louie",last_name: "Gohmert",bioguide_id: "G000552",disposition: "oppose",whipcount_id: "8029"},
{first_name: "Bob",last_name: "Goodlatte",bioguide_id: "G000289",disposition: "supports",whipcount_id: "7730"},
{first_name: "Paul",last_name: "Gosar",bioguide_id: "G000565",disposition: "did not vote",whipcount_id: "7714"},
{first_name: "Trey",last_name: "Gowdy",bioguide_id: "G000566",disposition: "supports",whipcount_id: "7962"},
{first_name: "Gwen",last_name: "Graham",bioguide_id: "G000575",disposition: "oppose",whipcount_id: "8105"},
{first_name: "Kay",last_name: "Granger",bioguide_id: "G000377",disposition: "supports",whipcount_id: "8083"},
{first_name: "Garret",last_name: "Graves",bioguide_id: "G000577",disposition: "supports",whipcount_id: "8085"},
{first_name: "Sam",last_name: "Graves",bioguide_id: "G000546",disposition: "supports",whipcount_id: "7813"},
{first_name: "Tom",last_name: "Graves",bioguide_id: "G000560",disposition: "supports",whipcount_id: "8189"},
{first_name: "Alan",last_name: "Grayson",bioguide_id: "G000556",disposition: "oppose",whipcount_id: "8132"},
{first_name: "Al",last_name: "Green",bioguide_id: "G000553",disposition: "oppose",whipcount_id: "8069"},
{first_name: "Gene",last_name: "Green",bioguide_id: "G000410",disposition: "oppose",whipcount_id: "7662"},
{first_name: "H.",last_name: "Griffith",bioguide_id: "G000568",disposition: "oppose",whipcount_id: "7748"},
{first_name: "Raul",last_name: "Grijalva",bioguide_id: "G000551",disposition: "oppose",whipcount_id: "7707"},
{first_name: "Glenn",last_name: "Grothman",bioguide_id: "G000576",disposition: "supports",whipcount_id: "7879"},
{first_name: "Frank",last_name: "Guinta",bioguide_id: "G000570",disposition: "supports",whipcount_id: "7969"},
{first_name: "Brett",last_name: "Guthrie",bioguide_id: "G000558",disposition: "supports",whipcount_id: "8033"},
{first_name: "Luis",last_name: "GutiÃ©rrez",bioguide_id: "G000535",disposition: "oppose",whipcount_id: "7860"},
{first_name: "Janice",last_name: "Hahn",bioguide_id: "H001063",disposition: "oppose",whipcount_id: "7985"},
{first_name: "Richard",last_name: "Hanna",bioguide_id: "H001051",disposition: "supports",whipcount_id: "8176"},
{first_name: "Cresent",last_name: "Hardy",bioguide_id: "H001070",disposition: "supports",whipcount_id: "8192"},
{first_name: "Gregg",last_name: "Harper",bioguide_id: "H001045",disposition: "supports",whipcount_id: "7851"},
{first_name: "Andy",last_name: "Harris",bioguide_id: "H001052",disposition: "oppose",whipcount_id: "8153"},
{first_name: "Vicky",last_name: "Hartzler",bioguide_id: "H001053",disposition: "supports",whipcount_id: "7804"},
{first_name: "Alcee",last_name: "Hastings",bioguide_id: "H000324",disposition: "oppose",whipcount_id: "7670"},
{first_name: "Denny",last_name: "Heck",bioguide_id: "H001064",disposition: "supports",whipcount_id: "8190"},
{first_name: "Joseph",last_name: "Heck",bioguide_id: "H001055",disposition: "supports",whipcount_id: "8067"},
{first_name: "Jeb",last_name: "Hensarling",bioguide_id: "H001036",disposition: "supports",whipcount_id: "8049"},
{first_name: "Jaime",last_name: "Herrera Beutler",bioguide_id: "H001056",disposition: "supports",whipcount_id: "7796"},
{first_name: "Jody",last_name: "Hice",bioguide_id: "H001071",disposition: "supports",whipcount_id: "7756"},
{first_name: "Brian",last_name: "Higgins",bioguide_id: "H001038",disposition: "oppose",whipcount_id: "7657"},
{first_name: "French",last_name: "Hill",bioguide_id: "H001072",disposition: "supports",whipcount_id: "7671"},
{first_name: "James",last_name: "Himes",bioguide_id: "H001047",disposition: "unknown",whipcount_id: "8082",phone: "202-225-5541"},
{first_name: "RubÃ©n",last_name: "Hinojosa",bioguide_id: "H000636",disposition: "unknown ",whipcount_id: "8099",phone: "202-225-2531"},
{first_name: "George",last_name: "Holding",bioguide_id: "H001065",disposition: "supports",whipcount_id: "7941"},
{first_name: "Michael",last_name: "Honda",bioguide_id: "H001034",disposition: "oppose",whipcount_id: "7855"},
{first_name: "Steny",last_name: "Hoyer",bioguide_id: "H000874",disposition: "oppose",whipcount_id: "8168"},
{first_name: "Richard",last_name: "Hudson",bioguide_id: "H001067",disposition: "supports ",whipcount_id: "7911"},
{first_name: "Tim",last_name: "Huelskamp",bioguide_id: "H001057",disposition: "supports",whipcount_id: "8007"},
{first_name: "Jared",last_name: "Huffman",bioguide_id: "H001068",disposition: "oppose",whipcount_id: "7747"},
{first_name: "Bill",last_name: "Huizenga",bioguide_id: "H001058",disposition: "supports",whipcount_id: "7656"},
{first_name: "Randy",last_name: "Hultgren",bioguide_id: "H001059",disposition: "supports",whipcount_id: "7926"},
{first_name: "Duncan",last_name: "Hunter",bioguide_id: "H001048",disposition: "oppose",whipcount_id: "8014"},
{first_name: "Will",last_name: "Hurd",bioguide_id: "H001073",disposition: "supports",whipcount_id: "8138"},
{first_name: "Robert",last_name: "Hurt",bioguide_id: "H001060",disposition: "supports",whipcount_id: "7724"},
{first_name: "Steve",last_name: "Israel",bioguide_id: "I000057",disposition: "oppose",whipcount_id: "8086"},
{first_name: "Darrell",last_name: "Issa",bioguide_id: "I000056",disposition: "supports",whipcount_id: "8009"},
{first_name: "Sheila",last_name: "Jackson Lee",bioguide_id: "J000032",disposition: "oppose",whipcount_id: "8110"},
{first_name: "Hakeem",last_name: "Jeffries",bioguide_id: "J000294",disposition: "oppose",whipcount_id: "8116"},
{first_name: "Evan",last_name: "Jenkins",bioguide_id: "J000297",disposition: "oppose",whipcount_id: "7908"},
{first_name: "Lynn",last_name: "Jenkins",bioguide_id: "J000290",disposition: "supports",whipcount_id: "8012"},
{first_name: "Bill",last_name: "Johnson",bioguide_id: "J000292",disposition: "supports",whipcount_id: "7715"},
{first_name: "Eddie",last_name: "Johnson",bioguide_id: "J000126",disposition: "unknown ",whipcount_id: "7668","202-225-8885"},
{first_name: "Henry",last_name: "Johnson",bioguide_id: "J000288",disposition: "oppose",whipcount_id: "7722"},
{first_name: "Sam",last_name: "Johnson",bioguide_id: "J000174",disposition: "supports",whipcount_id: "8039"},
{first_name: "David",last_name: "Jolly",bioguide_id: "J000296",disposition: "did not vote",whipcount_id: "7642"},
{first_name: "Walter",last_name: "Jones",bioguide_id: "J000255",disposition: "oppose",whipcount_id: "7887"},
{first_name: "Jim",last_name: "Jordan",bioguide_id: "J000289",disposition: "oppose",whipcount_id: "7703"},
{first_name: "David",last_name: "Joyce",bioguide_id: "J000295",disposition: "oppose",whipcount_id: "7769"},
{first_name: "Marcy",last_name: "Kaptur",bioguide_id: "K000009",disposition: "oppose",whipcount_id: "7735"},
{first_name: "John",last_name: "Katko",bioguide_id: "K000386",disposition: "oppose",whipcount_id: "7649"},
{first_name: "William",last_name: "Keating",bioguide_id: "K000375",disposition: "oppose",whipcount_id: "8140"},
{first_name: "Mike",last_name: "Kelly",bioguide_id: "K000376",disposition: "supports",whipcount_id: "7853"},
{first_name: "Robin",last_name: "Kelly",bioguide_id: "K000385",disposition: "oppose",whipcount_id: "7845"},
{first_name: "Trent",last_name: "Kelly",bioguide_id: "K000388",disposition: "did not vote",whipcount_id: "7841"},
{first_name: "Joseph",last_name: "Kennedy",bioguide_id: "K000379",disposition: "oppose",whipcount_id: "8112"},
{first_name: "Daniel",last_name: "Kildee",bioguide_id: "K000380",disposition: "oppose",whipcount_id: "7673"},
{first_name: "Derek",last_name: "Kilmer",bioguide_id: "K000381",disposition: "unknown",whipcount_id: "7820",phone: "202-225-5916"},
{first_name: "Ron",last_name: "Kind",bioguide_id: "K000188",disposition: "unknown ",whipcount_id: "7864",phone: "202-225-5506"},
{first_name: "Peter",last_name: "King",bioguide_id: "K000210",disposition: "supports",whipcount_id: "8080"},
{first_name: "Steve",last_name: "King",bioguide_id: "K000362",disposition: "supports",whipcount_id: "7815"},
{first_name: "Adam",last_name: "Kinzinger",bioguide_id: "K000378",disposition: "supports",whipcount_id: "7939"},
{first_name: "Ann",last_name: "Kirkpatrick",bioguide_id: "K000368",disposition: "oppose",whipcount_id: "7695"},
{first_name: "John",last_name: "Kline",bioguide_id: "K000363",disposition: "supports",whipcount_id: "7745"},
{first_name: "Steve",last_name: "Knight",bioguide_id: "K000387",disposition: "supports",whipcount_id: "7904"},
{first_name: "Ann",last_name: "Kuster",bioguide_id: "K000382",disposition: "oppose",whipcount_id: "7974"},
{first_name: "RaÃºl",last_name: "Labrador",bioguide_id: "L000573",disposition: "oppose",whipcount_id: "7826"},
{first_name: "Darin",last_name: "LaHood",bioguide_id: "L000585",disposition: "unknown",whipcount_id: "7950"},
{first_name: "Doug",last_name: "LaMalfa",bioguide_id: "L000578",disposition: "supports",whipcount_id: "7743"},
{first_name: "Doug",last_name: "Lamborn",bioguide_id: "L000564",disposition: "supports",whipcount_id: "8051"},
{first_name: "Leonard",last_name: "Lance",bioguide_id: "L000567",disposition: "supports",whipcount_id: "8013"},
{first_name: "James",last_name: "Langevin",bioguide_id: "L000559",disposition: "oppose",whipcount_id: "7940"},
{first_name: "Rick",last_name: "Larsen",bioguide_id: "L000560",disposition: "unknown",whipcount_id: "7785",phone: "202-225-2605"},
{first_name: "John",last_name: "Larson",bioguide_id: "L000557",disposition: "oppose",whipcount_id: "8070"},
{first_name: "Robert",last_name: "Latta",bioguide_id: "L000566",disposition: "supports",whipcount_id: "7709"},
{first_name: "Brenda",last_name: "Lawrence",bioguide_id: "L000581",disposition: "oppose",whipcount_id: "7729"},
{first_name: "Barbara",last_name: "Lee",bioguide_id: "L000551",disposition: "oppose",whipcount_id: "7827"},
{first_name: "Sander",last_name: "Levin",bioguide_id: "L000263",disposition: "oppose",whipcount_id: "7699"},
{first_name: "John",last_name: "Lewis",bioguide_id: "L000287",disposition: "oppose",whipcount_id: "7727"},
{first_name: "Ted",last_name: "Lieu",bioguide_id: "L000582",disposition: "oppose",whipcount_id: "7942"},
{first_name: "Daniel",last_name: "Lipinski",bioguide_id: "L000563",disposition: "oppose",whipcount_id: "7854"},
{first_name: "Frank",last_name: "LoBiondo",bioguide_id: "L000554",disposition: "oppose",whipcount_id: "7988"},
{first_name: "David",last_name: "Loebsack",bioguide_id: "L000565",disposition: "oppose",whipcount_id: "7805"},
{first_name: "Zoe",last_name: "Lofgren",bioguide_id: "L000397",disposition: "oppose",whipcount_id: "7868"},
{first_name: "Billy",last_name: "Long",bioguide_id: "L000576",disposition: "supports",whipcount_id: "7818"},
{first_name: "Barry",last_name: "Loudermilk",bioguide_id: "L000583",disposition: "supports",whipcount_id: "7760"},
{first_name: "Mia",last_name: "Love",bioguide_id: "L000584",disposition: "supports",whipcount_id: "8185"},
{first_name: "Alan",last_name: "Lowenthal",bioguide_id: "L000579",disposition: "oppose",whipcount_id: "8001"},
{first_name: "Nita",last_name: "Lowey",bioguide_id: "L000480",disposition: "oppose",whipcount_id: "8160"},
{first_name: "Frank",last_name: "Lucas",bioguide_id: "L000491",disposition: "supports ",whipcount_id: "7800"},
{first_name: "Blaine",last_name: "Luetkemeyer",bioguide_id: "L000569",disposition: "supports ",whipcount_id: "7797"},
{first_name: "Ben",last_name: "LujÃ¡n",bioguide_id: "L000570",disposition: "oppose",whipcount_id: "8054"},
{first_name: "Michelle",last_name: "Lujan Grisham",bioguide_id: "L000580",disposition: "oppose",whipcount_id: "8040"},
{first_name: "Cynthia",last_name: "Lummis",bioguide_id: "L000571",disposition: "oppose",whipcount_id: "7910"},
{first_name: "Stephen",last_name: "Lynch",bioguide_id: "L000562",disposition: "oppose",whipcount_id: "8135"},
{first_name: "Tom",last_name: "MacArthur",bioguide_id: "M001193",disposition: "oppose",whipcount_id: "7994"},
{first_name: "Carolyn",last_name: "Maloney",bioguide_id: "M000087",disposition: "oppose",whipcount_id: "8139"},
{first_name: "Sean",last_name: "Maloney",bioguide_id: "M001185",disposition: "oppose",whipcount_id: "8163"},
{first_name: "Kenny",last_name: "Marchant",bioguide_id: "M001158",disposition: "supports ",whipcount_id: "8143"},
{first_name: "Tom",last_name: "Marino",bioguide_id: "M001179",disposition: "supports",whipcount_id: "7885"},
{first_name: "Thomas",last_name: "Massie",bioguide_id: "M001184",disposition: "oppose",whipcount_id: "8041"},
{first_name: "Doris",last_name: "Matsui",bioguide_id: "M001163",disposition: "oppose",whipcount_id: "7773"},
{first_name: "Kevin",last_name: "McCarthy",bioguide_id: "M001165",disposition: "supports ",whipcount_id: "7892"},
{first_name: "Michael",last_name: "McCaul",bioguide_id: "M001157",disposition: "supports",whipcount_id: "8074"},
{first_name: "Tom",last_name: "McClintock",bioguide_id: "M001177",disposition: "supports ",whipcount_id: "7759"},
{first_name: "Betty",last_name: "McCollum",bioguide_id: "M001143",disposition: "oppose",whipcount_id: "7755"},
{first_name: "Jim",last_name: "McDermott",bioguide_id: "M000404",disposition: "oppose",whipcount_id: "7828"},
{first_name: "James",last_name: "McGovern",bioguide_id: "M000312",disposition: "oppose",whipcount_id: "8100"},
{first_name: "Patrick",last_name: "McHenry",bioguide_id: "M001156",disposition: "supports",whipcount_id: "7922"},
{first_name: "David",last_name: "McKinley",bioguide_id: "M001180",disposition: "oppose",whipcount_id: "7897"},
{first_name: "Cathy",last_name: "McMorris Rodgers",bioguide_id: "M001159",disposition: "supports ",whipcount_id: "7811"},
{first_name: "Jerry",last_name: "McNerney",bioguide_id: "M001166",disposition: "oppose",whipcount_id: "7792"},
{first_name: "Martha",last_name: "McSally",bioguide_id: "M001197",disposition: "supports ",whipcount_id: "7701"},
{first_name: "Mark",last_name: "Meadows",bioguide_id: "M001187",disposition: "oppose",whipcount_id: "7929"},
{first_name: "Patrick",last_name: "Meehan",bioguide_id: "M001181",disposition: "supports ",whipcount_id: "7872"},
{first_name: "Gregory",last_name: "Meeks",bioguide_id: "M001137",disposition: "unknown",whipcount_id: "8097",phone: "202-225-3461"},
{first_name: "Grace",last_name: "Meng",bioguide_id: "M001188",disposition: "oppose",whipcount_id: "8103"},
{first_name: "Luke",last_name: "Messer",bioguide_id: "M001189",disposition: "supports",whipcount_id: "7987"},
{first_name: "John",last_name: "Mica",bioguide_id: "M000689",disposition: "supports",whipcount_id: "8125"},
{first_name: "Candice",last_name: "Miller",bioguide_id: "M001150",disposition: "supports ",whipcount_id: "7706"},
{first_name: "Jeff",last_name: "Miller",bioguide_id: "M001144",disposition: "supports ",whipcount_id: "8101"},
{first_name: "John",last_name: "Moolenaar",bioguide_id: "M001194",disposition: "supports ",whipcount_id: "7667"},
{first_name: "Alex",last_name: "Mooney",bioguide_id: "M001195",disposition: "oppose",whipcount_id: "7902"},
{first_name: "Gwen",last_name: "Moore",bioguide_id: "M001160",disposition: "oppose",whipcount_id: "7870"},
{first_name: "Seth",last_name: "Moulton",bioguide_id: "M001196",disposition: "oppose",whipcount_id: "8123"},
{first_name: "Markwayne",last_name: "Mullin",bioguide_id: "M001190",disposition: "supports",whipcount_id: "7798"},
{first_name: "Mick",last_name: "Mulvaney",bioguide_id: "M001182",disposition: "oppose",whipcount_id: "7967"},
{first_name: "Patrick",last_name: "Murphy",bioguide_id: "M001191",disposition: "oppose",whipcount_id: "7659"},
{first_name: "Tim",last_name: "Murphy",bioguide_id: "M001151",disposition: "supports",whipcount_id: "7924"},
{first_name: "Jerrold",last_name: "Nadler",bioguide_id: "N000002",disposition: "oppose",whipcount_id: "8126"},
{first_name: "Grace",last_name: "Napolitano",bioguide_id: "N000179",disposition: "oppose",whipcount_id: "7938"},
{first_name: "Richard",last_name: "Neal",bioguide_id: "N000015",disposition: "oppose",whipcount_id: "8095"},
{first_name: "Randy",last_name: "Neugebauer",bioguide_id: "N000182",disposition: "supports",whipcount_id: "8114"},
{first_name: "Dan",last_name: "Newhouse",bioguide_id: "N000189",disposition: "supports ",whipcount_id: "7803"},
{first_name: "Kristi",last_name: "Noem",bioguide_id: "N000184",disposition: "supports ",whipcount_id: "7976"},
{first_name: "Richard",last_name: "Nolan",bioguide_id: "N000127",disposition: "oppose",whipcount_id: "7777"},
{first_name: "Donald",last_name: "Norcross",bioguide_id: "N000188",disposition: "oppose",whipcount_id: "7981"},
{first_name: "Richard",last_name: "Nugent",bioguide_id: "N000185",disposition: "oppose",whipcount_id: "8142"},
{first_name: "Devin",last_name: "Nunes",bioguide_id: "N000181",disposition: "supports",whipcount_id: "7888"},
{first_name: "Beto",last_name: "O'Rourke",bioguide_id: "O000170",disposition: "unknown ",whipcount_id: "8102",phone: "202-225-4831"},
{first_name: "Pete",last_name: "Olson",bioguide_id: "O000168",disposition: "supports",whipcount_id: "8134"},
{first_name: "Steven",last_name: "Palazzo",bioguide_id: "P000601",disposition: "supports",whipcount_id: "7856"},
{first_name: "Frank",last_name: "Pallone",bioguide_id: "P000034",disposition: "oppose",whipcount_id: "8008"},
{first_name: "Gary",last_name: "Palmer",bioguide_id: "P000609",disposition: "oppose",whipcount_id: "7658"},
{first_name: "Bill",last_name: "Pascrell",bioguide_id: "P000096",disposition: "oppose",whipcount_id: "8021"},
{first_name: "Erik",last_name: "Paulsen",bioguide_id: "P000594",disposition: "supports",whipcount_id: "7750"},
{first_name: "Donald",last_name: "Payne",bioguide_id: "P000604",disposition: "did not vote",whipcount_id: "8025"},
{first_name: "Stevan",last_name: "Pearce",bioguide_id: "P000588",disposition: "oppose",whipcount_id: "8048"},
{first_name: "Nancy",last_name: "Pelosi",bioguide_id: "P000197",disposition: "",whipcount_id: "7817"},
{first_name: "Ed",last_name: "Perlmutter",bioguide_id: "P000593",disposition: "oppose",whipcount_id: "8063"},
{first_name: "Scott",last_name: "Perry",bioguide_id: "P000605",disposition: "oppose",whipcount_id: "7858"},
{first_name: "Scott",last_name: "Peters",bioguide_id: "P000608",disposition: "unknown ",whipcount_id: "8023",phone: "202-225-0508"},
{first_name: "Collin",last_name: "Peterson",bioguide_id: "P000258",disposition: "oppose",whipcount_id: "7768"},
{first_name: "Chellie",last_name: "Pingree",bioguide_id: "P000597",disposition: "oppose",whipcount_id: "8181"},
{first_name: "Robert",last_name: "Pittenger",bioguide_id: "P000606",disposition: "supports",whipcount_id: "7917"},
{first_name: "Joseph",last_name: "Pitts",bioguide_id: "P000373",disposition: "supports",whipcount_id: "7916"},
{first_name: "Mark",last_name: "Pocan",bioguide_id: "P000607",disposition: "oppose",whipcount_id: "7859"},
{first_name: "Ted",last_name: "Poe",bioguide_id: "P000592",disposition: "supports",whipcount_id: "8034"},
{first_name: "Bruce",last_name: "Poliquin",bioguide_id: "P000611",disposition: "oppose",whipcount_id: "7648"},
{first_name: "Jared",last_name: "Polis",bioguide_id: "P000598",disposition: "unknown ",whipcount_id: "8037",phone: "202-225-2161"},
{first_name: "Mike",last_name: "Pompeo",bioguide_id: "P000602",disposition: "supports",whipcount_id: "8020"},
{first_name: "Bill",last_name: "Posey",bioguide_id: "P000599",disposition: "oppose",whipcount_id: "8130"},
{first_name: "David",last_name: "Price",bioguide_id: "P000523",disposition: "oppose",whipcount_id: "7896"},
{first_name: "Tom",last_name: "Price",bioguide_id: "P000591",disposition: "supports",whipcount_id: "7733"},
{first_name: "Mike",last_name: "Quigley",bioguide_id: "Q000023",disposition: "unknown ",whipcount_id: "7867",phone: "202-225-4061"},
{first_name: "Charles",last_name: "Rangel",bioguide_id: "R000053",disposition: "oppose",whipcount_id: "8144"},
{first_name: "John",last_name: "Ratcliffe",bioguide_id: "R000601",disposition: "supports",whipcount_id: "8044"},
{first_name: "Tom",last_name: "Reed",bioguide_id: "R000585",disposition: "supports",whipcount_id: "8178"},
{first_name: "David",last_name: "Reichert",bioguide_id: "R000578",disposition: "supports",whipcount_id: "7835"},
{first_name: "James",last_name: "Renacci",bioguide_id: "R000586",disposition: "supports",whipcount_id: "7780"},
{first_name: "Reid",last_name: "Ribble",bioguide_id: "R000587",disposition: "supports",whipcount_id: "7891"},
{first_name: "Kathleen",last_name: "Rice",bioguide_id: "R000602",disposition: "unknown ",whipcount_id: "8091",phone: "202-225-5516"},
{first_name: "Tom",last_name: "Rice",bioguide_id: "R000597",disposition: "supports",whipcount_id: "8191"},
{first_name: "Cedric",last_name: "Richmond",bioguide_id: "R000588",disposition: "oppose",whipcount_id: "8066"},
{first_name: "Edward",last_name: "Rigell",bioguide_id: "R000589",disposition: "supports",whipcount_id: "7708"},
{first_name: "Martha",last_name: "Roby",bioguide_id: "R000591",disposition: "supports",whipcount_id: "7644"},
{first_name: "David",last_name: "Roe",bioguide_id: "R000582",disposition: "supports",whipcount_id: "7980"},
{first_name: "Harold",last_name: "Rogers",bioguide_id: "R000395",disposition: "supports",whipcount_id: "8046"},
{first_name: "Mike",last_name: "Rogers",bioguide_id: "R000575",disposition: "supports ",whipcount_id: "7646"},
{first_name: "Dana",last_name: "Rohrabacher",bioguide_id: "R000409",disposition: "oppose",whipcount_id: "8004"},
{first_name: "Todd",last_name: "Rokita",bioguide_id: "R000592",disposition: "supports ",whipcount_id: "7977"},
{first_name: "Thomas",last_name: "Rooney",bioguide_id: "R000583",disposition: "supports ",whipcount_id: "7655"},
{first_name: "Ileana",last_name: "Ros-Lehtinen",bioguide_id: "R000435",disposition: "supports",whipcount_id: "8187"},
{first_name: "Peter",last_name: "Roskam",bioguide_id: "R000580",disposition: "supports ",whipcount_id: "7876"},
{first_name: "Dennis",last_name: "Ross",bioguide_id: "R000593",disposition: "supports ",whipcount_id: "7647"},
{first_name: "Keith",last_name: "Rothfus",bioguide_id: "R000598",disposition: "oppose",whipcount_id: "7895"},
{first_name: "David",last_name: "Rouzer",bioguide_id: "R000603",disposition: "supports ",whipcount_id: "7905"},
{first_name: "Lucille",last_name: "Roybal-Allard",bioguide_id: "R000486",disposition: "oppose",whipcount_id: "7970"},
{first_name: "Edward",last_name: "Royce",bioguide_id: "R000487",disposition: "supports ",whipcount_id: "7966"},
{first_name: "Raul",last_name: "Ruiz",bioguide_id: "R000599",disposition: "oppose",whipcount_id: "7954"},
{first_name: "C.",last_name: "Ruppersberger",bioguide_id: "R000576",disposition: "oppose",whipcount_id: "8158"},
{first_name: "Bobby",last_name: "Rush",bioguide_id: "R000515",disposition: "oppose",whipcount_id: "7837"},
{first_name: "Steve",last_name: "Russell",bioguide_id: "R000604",disposition: "oppose",whipcount_id: "7812"},
{first_name: "Paul",last_name: "Ryan",bioguide_id: "R000570",disposition: "oppose",whipcount_id: "7850"},
{first_name: "Tim",last_name: "Ryan",bioguide_id: "R000577",disposition: "oppose",whipcount_id: "7762"},
{first_name: "Linda",last_name: "SÃ¡nchez",bioguide_id: "S001156",disposition: "oppose",whipcount_id: "7961"},
{first_name: "Matt",last_name: "Salmon",bioguide_id: "S000018",disposition: "supports ",whipcount_id: "7718"},
{first_name: "Loretta",last_name: "Sanchez",bioguide_id: "S000030",disposition: "oppose",whipcount_id: "7996"},
{first_name: "Marshall",last_name: "Sanford",bioguide_id: "S000051",disposition: "supports ",whipcount_id: "7947"},
{first_name: "John",last_name: "Sarbanes",bioguide_id: "S001168",disposition: "oppose",whipcount_id: "8162"},
{first_name: "Steve",last_name: "Scalise",bioguide_id: "S001176",disposition: "supports ",whipcount_id: "8058"},
{first_name: "Janice",last_name: "Schakowsky",bioguide_id: "S001145",disposition: "oppose",whipcount_id: "7894"},
{first_name: "Adam",last_name: "Schiff",bioguide_id: "S001150",disposition: "oppose",whipcount_id: "7921"},
{first_name: "Kurt",last_name: "Schrader",bioguide_id: "S001180",disposition: "unknown",whipcount_id: "7839",phone: "202-225-5711"},
{first_name: "David",last_name: "Schweikert",bioguide_id: "S001183",disposition: "supports ",whipcount_id: "7726"},
{first_name: "Austin",last_name: "Scott",bioguide_id: "S001189",disposition: "supports ",whipcount_id: "7744"},
{first_name: "David",last_name: "Scott",bioguide_id: "S001157",disposition: "oppose",whipcount_id: "7770"},
{first_name: "Robert",last_name: "Scott",bioguide_id: "S000185",disposition: "oppose",whipcount_id: "7713"},
{first_name: "F.",last_name: "Sensenbrenner",bioguide_id: "S000244",disposition: "supports ",whipcount_id: "7874"},
{first_name: "JosÃ©",last_name: "Serrano",bioguide_id: "S000248",disposition: "oppose",whipcount_id: "8152"},
{first_name: "Pete",last_name: "Sessions",bioguide_id: "S000250",disposition: "supports ",whipcount_id: "7679"},
{first_name: "Terri",last_name: "Sewell",bioguide_id: "S001185",disposition: "unknown ",whipcount_id: "7664",phone: "202-225-2665"},
{first_name: "Brad",last_name: "Sherman",bioguide_id: "S000344",disposition: "oppose",whipcount_id: "7930"},
{first_name: "John",last_name: "Shimkus",bioguide_id: "S000364",disposition: "supports ",whipcount_id: "7932"},
{first_name: "Bill",last_name: "Shuster",bioguide_id: "S001154",disposition: "supports ",whipcount_id: "7881"},
{first_name: "Michael",last_name: "Simpson",bioguide_id: "S001148",disposition: "supports",whipcount_id: "7833"},
{first_name: "Kyrsten",last_name: "Sinema",bioguide_id: "S001191",disposition: "oppose",whipcount_id: "8188"},
{first_name: "Albio",last_name: "Sires",bioguide_id: "S001165",disposition: "oppose",whipcount_id: "8018"},
{first_name: "Louise",last_name: "Slaughter",bioguide_id: "S000480",disposition: "oppose",whipcount_id: "7653"},
{first_name: "Adam",last_name: "Smith",bioguide_id: "S000510",disposition: "oppose",whipcount_id: "7842"},
{first_name: "Adrian",last_name: "Smith",bioguide_id: "S001172",disposition: "supports",whipcount_id: "7963"},
{first_name: "Christopher",last_name: "Smith",bioguide_id: "S000522",disposition: "oppose",whipcount_id: "7999"},
{first_name: "Jason",last_name: "Smith",bioguide_id: "S001195",disposition: "supports",whipcount_id: "7823"},
{first_name: "Lamar",last_name: "Smith",bioguide_id: "S000583",disposition: "supports",whipcount_id: "8128"},
{first_name: "Jackie",last_name: "Speier",bioguide_id: "S001175",disposition: "oppose",whipcount_id: "7832"},
{first_name: "Elise",last_name: "Stefanik",bioguide_id: "S001196",disposition: "supports",whipcount_id: "8173"},
{first_name: "Chris",last_name: "Stewart",bioguide_id: "S001192",disposition: "supports",whipcount_id: "7691"},
{first_name: "Steve",last_name: "Stivers",bioguide_id: "S001187",disposition: "supports",whipcount_id: "7774"},
{first_name: "Marlin",last_name: "Stutzman",bioguide_id: "S001188",disposition: "supports",whipcount_id: "7971"},
{first_name: "Eric",last_name: "Swalwell",bioguide_id: "S001193",disposition: "oppose",whipcount_id: "7838"},
{first_name: "Mark",last_name: "Takano",bioguide_id: "T000472",disposition: "oppose",whipcount_id: "7975"},
{first_name: "Bennie",last_name: "Thompson",bioguide_id: "T000193",disposition: "oppose",whipcount_id: "7846"},
{first_name: "Glenn",last_name: "Thompson",bioguide_id: "T000467",disposition: "supports",whipcount_id: "7863"},
{first_name: "Mike",last_name: "Thompson",bioguide_id: "T000460",disposition: "oppose",whipcount_id: "7766"},
{first_name: "Mac",last_name: "Thornberry",bioguide_id: "T000238",disposition: "supports",whipcount_id: "8088"},
{first_name: "Patrick",last_name: "Tiberi",bioguide_id: "T000462",disposition: "supports",whipcount_id: "7752"},
{first_name: "Scott",last_name: "Tipton",bioguide_id: "T000470",disposition: "supports",whipcount_id: "8043"},
{first_name: "Dina",last_name: "Titus",bioguide_id: "T000468",disposition: "oppose",whipcount_id: "8059"},
{first_name: "Paul",last_name: "Tonko",bioguide_id: "T000469",disposition: "oppose",whipcount_id: "8170"},
{first_name: "Norma",last_name: "Torres",bioguide_id: "T000474",disposition: "oppose",whipcount_id: "7949"},
{first_name: "Dave",last_name: "Trott",bioguide_id: "T000475",disposition: "supports",whipcount_id: "7711"},
{first_name: "Niki",last_name: "Tsongas",bioguide_id: "T000465",disposition: "oppose",whipcount_id: "8107"},
{first_name: "Michael",last_name: "Turner",bioguide_id: "T000463",disposition: "supports",whipcount_id: "7741"},
{first_name: "Fred",last_name: "Upton",bioguide_id: "U000031",disposition: "supports",whipcount_id: "7680"},
{first_name: "David",last_name: "Valadao",bioguide_id: "V000129",disposition: "supports",whipcount_id: "7882"},
{first_name: "Chris",last_name: "Van Hollen",bioguide_id: "V000128",disposition: "oppose",whipcount_id: "8180"},
{first_name: "Juan",last_name: "Vargas",bioguide_id: "V000130",disposition: "oppose",whipcount_id: "8019"},
{first_name: "Marc",last_name: "Veasey",bioguide_id: "V000131",disposition: "oppose",whipcount_id: "8193"},
{first_name: "Filemon",last_name: "Vela",bioguide_id: "V000132",disposition: "oppose",whipcount_id: "8194"},
{first_name: "Nydia",last_name: "VelÃ¡zquez",bioguide_id: "V000081",disposition: "oppose",whipcount_id: "8109"},
{first_name: "Peter",last_name: "Visclosky",bioguide_id: "V000108",disposition: "oppose",whipcount_id: "7960"},
{first_name: "Ann",last_name: "Wagner",bioguide_id: "W000812",disposition: "supports",whipcount_id: "7787"},
{first_name: "Tim",last_name: "Walberg",bioguide_id: "W000798",disposition: "supports",whipcount_id: "7686"},
{first_name: "Greg",last_name: "Walden",bioguide_id: "W000791",disposition: "supports",whipcount_id: "7822"},
{first_name: "Mark",last_name: "Walker",bioguide_id: "W000819",disposition: "supports",whipcount_id: "7903"},
{first_name: "Jackie",last_name: "Walorski",bioguide_id: "W000813",disposition: "supports",whipcount_id: "7965"},
{first_name: "Mimi",last_name: "Walters",bioguide_id: "W000820",disposition: "supports",whipcount_id: "7990"},
{first_name: "Timothy",last_name: "Walz",bioguide_id: "W000799",disposition: "oppose",whipcount_id: "7740"},
{first_name: "Debbie",last_name: "Wasserman Schultz",bioguide_id: "W000797",disposition: "unknown ",whipcount_id: "7687",phone: "202-225-7931"},
{first_name: "Maxine",last_name: "Waters",bioguide_id: "W000187",disposition: "oppose",whipcount_id: "7982"},
{first_name: "Bonnie",last_name: "Watson Coleman",bioguide_id: "W000822",disposition: "oppose",whipcount_id: "8032"},
{first_name: "Randy",last_name: "Weber",bioguide_id: "W000814",disposition: "supports",whipcount_id: "8094"},
{first_name: "Daniel",last_name: "Webster",bioguide_id: "W000806",disposition: "oppose",whipcount_id: "8137"},
{first_name: "Peter",last_name: "Welch",bioguide_id: "W000800",disposition: "oppose",whipcount_id: "7771"},
{first_name: "Brad",last_name: "Wenstrup",bioguide_id: "W000815",disposition: "supports",whipcount_id: "7690"},
{first_name: "Bruce",last_name: "Westerman",bioguide_id: "W000821",disposition: "supports",whipcount_id: "7682"},
{first_name: "Lynn",last_name: "Westmoreland",bioguide_id: "W000796",disposition: "oppose",whipcount_id: "7716"},
{first_name: "Ed",last_name: "Whitfield",bioguide_id: "W000413",disposition: "supports",whipcount_id: "8026"},
{first_name: "Roger",last_name: "Williams",bioguide_id: "W000816",disposition: "supports",whipcount_id: "8147"},
{first_name: "Frederica",last_name: "Wilson",bioguide_id: "W000808",disposition: "oppose",whipcount_id: "7693"},
{first_name: "Joe",last_name: "Wilson",bioguide_id: "W000795",disposition: "supports",whipcount_id: "7951"},
{first_name: "Robert",last_name: "Wittman",bioguide_id: "W000804",disposition: "oppose",whipcount_id: "7702"},
{first_name: "Steve",last_name: "Womack",bioguide_id: "W000809",disposition: "supports",whipcount_id: "7678"},
{first_name: "Rob",last_name: "Woodall",bioguide_id: "W000810",disposition: "supports",whipcount_id: "7737"},
{first_name: "John",last_name: "Yarmuth",bioguide_id: "Y000062",disposition: "oppose",whipcount_id: "8038"},
{first_name: "Kevin",last_name: "Yoder",bioguide_id: "Y000063",disposition: "supports",whipcount_id: "8015"},
{first_name: "Ted",last_name: "Yoho",bioguide_id: "Y000065",disposition: "supports",whipcount_id: "8108"},
{first_name: "David",last_name: "Young",bioguide_id: "Y000066",disposition: "supports",whipcount_id: "7810"},
{first_name: "Don",last_name: "Young",bioguide_id: "Y000033",disposition: "did not vote",whipcount_id: "7641"},
{first_name: "Todd",last_name: "Young",bioguide_id: "Y000064",disposition: "supports",whipcount_id: "8002"},
{first_name: "Lee",last_name: "Zeldin",bioguide_id: "Z000017",disposition: "oppose",whipcount_id: "8073"},
{first_name: "Ryan",last_name: "Zinke",bioguide_id: "Z000018",disposition: "supports",whipcount_id: "7865"},
]
