# Setup
title:               Credo TPP Whipcount
tagline:             'tagline?'
description:         'description?'
url:                 http://www.tppwhipcount.com
baseurl:             /

# About/contact
author:
  name:              Charlie Furman
  url:               https://twitter.com/digitalcharlie
  email:             furman.jr@gmail.com

